date: '2021-10-12'
sections:
  security_fixes:
    - '패키지가 최신 보안 버전으로 업데이트되었습니다. {% comment %} https://github.com/github/enterprise2/pull/27118, https://github.com/github/enterprise2/pull/27110 {% endcomment %}'
  bugs:
    - '지나치게 제한적인 가상 메모리 또는 CPU 시간 제한으로 인해 사용자 지정 사전 수신 후크가 실패할 수 있습니다. {% comment %} https://github.com/github/enterprise2/pull/26973, https://github.com/github/enterprise2/pull/26955 {% endcomment %}'
    - 'GitHub Enterprise Server 클러스터링 구성에서 종속성 그래프 설정이 잘못 적용되었을 수 있습니다. {% comment %} https://github.com/github/enterprise2/pull/26981, https://github.com/github/enterprise2/pull/26861 {% endcomment %}'
    - '`ghe-cleanup-settings`를 사용하여 기존 구성 설정을 모두 지우려는 시도에서 관리 콘솔 서비스를 다시 시작하지 못했습니다. {% comment %} https://github.com/github/enterprise2/pull/26988, https://github.com/github/enterprise2/pull/26901 {% endcomment %}'
    - '`ghe-repl-teardown`을 통한 복제 해제 중에 Memcached가 다시 시작되지 않았습니다. {% comment %} https://github.com/github/enterprise2/pull/26994, https://github.com/github/enterprise2/pull/26983 {% endcomment %}'
    - '부하가 높은 기간 동안 업스트림 서비스가 내부 상태 확인에 실패하면 사용자는 HTTP 503 상태 코드를 수신합니다. {% comment %} https://github.com/github/enterprise2/pull/27083, https://github.com/github/enterprise2/pull/26999 {% endcomment %}'
    - '사전 수신 후크 환경에서는 Alpine의 BusyBox를 통해 cat 명령을 호출하는 것이 금지되었습니다. {% comment %} https://github.com/github/enterprise2/pull/27116, https://github.com/github/enterprise2/pull/27094 {% endcomment %}'
    - '기본 클러스터 데이터 센터에서 보조 클러스터 데이터 센터로의 장애 조치(failover)는 성공했지만 원래 기본 클러스터 데이터 센터로의 다시 장애 조치 시 Elasticsearch 인덱스를 승격하지 못했습니다. {% comment %} https://github.com/github/github/pull/193182, https://github.com/github/github/pull/192447 {% endcomment %}'
    - '조직에 대한 팀 페이지의 "팀 가져오기" 단추가 HTTP 404를 반환했습니다. {% comment %} https://github.com/github/github/pull/193303 {% endcomment %}'
    - 'API를 사용해 비밀 검사를 비활성화하여 속성이 올바르게 비활성화되었지만 HTTP 422 및 오류 메시지가 잘못 반환되었습니다. {% comment %} https://github.com/github/github/pull/193455, https://github.com/github/github/pull/192907 {% endcomment %}'
    - '일부 경우 `유휴 사용자` 페이지를 보려고 하는 GitHub Enterprise 관리자가 `502 잘못된 게이트웨이` 또는 `504 게이트웨이 시간 초과` 응답을 수신했습니다. {% comment %} https://github.com/github/github/pull/194262, https://github.com/github/github/pull/193609 {% endcomment %}'
    - '`SynchronizePullRequestJob` 작업 수의 증가로 인해 특정 고부하 상황에서 성능에 부정적인 영향이 있었습니다. {% comment %} https://github.com/github/github/pull/195256, https://github.com/github/github/pull/194591 {% endcomment %}'
    - '비밀 검사를 위해 생성된 사용자 정의 패턴은 삭제된 후에도 계속 검사됩니다. {% comment %} https://github.com/github/token-scanning-service/pull/1039, https://github.com/github/token-scanning-service/pull/822 {% endcomment %}'
  changes:
    - '이제 GitHub 앱에서 API와 일관되게 리포지토리에서 비밀 검사 기능을 설정합니다. {% comment %} https://github.com/github/github/pull/193456, https://github.com/github/github/pull/193125 {% endcomment %}'
  known_issues:
    - "사용자 없이 새로 설정된 {% data variables.product.prodname_ghe_server %}에서 공격자는 첫 번째 관리 사용자를 만들 수 있습니다."
    - 사용자 지정 방화벽 규칙은 업그레이드 프로세스 중에 제거됩니다.
    - "Git LFS 추적 파일[웹 인터페이스를 통해 업로드됨](https://github.com/blog/2105-upload-files-to-your-repositories)이 리포지토리에 직접 잘못 추가되었습니다."
    - 이슈에 동일한 리포지토리의 Blob에 대한 고정 링크가 포함되었지만 Blob의 파일 경로가 255자보다 긴 경우 해당 이슈를 종료할 수 없습니다.
    - GitHub Connect에서 “사용자가 GitHub.com을 검색할 수 있음”이 사용하도록 설정되면 프라이빗 및 내부 리포지토리의 이슈가 GitHub.com 검색 결과에 포함되지 않습니다.
    - "{% data variables.product.prodname_registry %} npm 레지스트리는 더 이상 메타데이터 응답에서 시간 값을 반환하지 않습니다. 이 작업은 성능을 크게 향상시키기 위해 수행되었습니다. 메타데이터 응답의 일부로 시간 값을 반환하는 데 필요한 모든 데이터를 계속 보유하고 있으며, 기존 성능 이슈가 해결되면 이 값의 반환을 다시 시작할 예정입니다."
    - 사전 수신 후크 처리에만 해당되는 리소스 한도로 인해 일부 사전 수신 후크가 실패할 수 있습니다.
    - '{% data reusables.release-notes.ghas-3.4-secret-scanning-known-issue %}'
