date: '2021-06-10'
sections:
  security_fixes:
    - Пакеты обновлены до последних версий систем безопасности.
  bugs:
    - "SVN 1.7 и более старые клиенты отображали ошибку при использовании команд \"svn co\" и \"svn export\"."
    - "При доступе к репозиторию через административную оболочку с использованием \"ghe-repo <владелец>/<имя_репозитория>\" происходит зависание."
    - После обновления у пользователей снижалась доступность при интенсивном потреблении из-за слишком частого перезапуска служб. Это происходило из-за несоответствия времени ожидания в конфигурации Nomad и внутренних службах.
    - "В некоторых случаях выполнение \"ghe-repl-status\" после настройки GitHub Actions выдавало ошибку и происходил сбой \"ghe-actions-teardown\"."
    - 'В некоторых ситуациях при использовании "ghe-dbconsole" возвращались ошибки.'
    - "При сбое импорта организаций или репозиториев из источников вне GitHub могла выдаваться ошибка \"undefined method '[]' for nil:NilClass\" (неопределенный метод \"[]\" for nil:NilClass)."
    - "Если имя профиля GitHub не соответствовало значению атрибута, сопоставленного полю \"Full name\" (Полное имя) в консоли управления, возможно было непреднамеренное изменение имен при проверке подлинности SAML."
    - "При обновлении экземпляра, где ранее использовался выпуск 2.13, но не 2.14, возникала ошибка миграции базы данных, связанная с переносом данных \"AddRepositoryIdToCheckRuns\"."
  changes:
    - "Пользователи API GraphQL могут запрашивать общедоступное поле \"closingIssuesReferences\" в объекте \"PullRequest\". Это поле позволяет получить проблемы, которые при слиянии связанного запроса на вытягивание автоматически будут закрыты. Такой подход также позволит переносить эти данные в будущем в рамках высокоточного процесса миграции."
  known_issues:
    - "Реестр npm для {% data variables.product.prodname_registry %} больше не возвращает значение времени в ответах с метаданными. Это изменение позволяет существенно улучшить производительность. Все данные, необходимые для возврата значения времени в ответе с метаданными, по-прежнему доступны, и мы возобновим этот возврат в будущем, как только имеющиеся проблемы с производительностью будут решены."
    - "Злоумышленник мог создать первого пользователя с правами администратора на новом, только что настроенном сервере {% data variables.product.prodname_ghe_server %}, не имеющем пользователей."
    - Настраиваемые правила брандмауэра удаляются в процессе обновления.
    - "Отслеживаемые файлы Git LFS, [отправленные через веб-интерфейс](https://github.com/blog/2105-upload-files-to-your-repositories), ошибочно добавлялись напрямую в репозиторий."
    - "Невозможно закрывать проблемы, если они содержат постоянную ссылку на BLOB-объект в том же репозитории с путем, длина которого превышает 255 символов."
    - "Когда в GitHub Connect включен параметр \"Пользователи могут выполнять поиск на GitHub.com\", результаты поиска на GitHub.com не включают проблемы в частных и внутренних репозиториях."
    - |После обновления версии с 3.0.x до 3.1.x в некоторых ситуациях был возможен сбой GitHub Actions с ошибкой "An unexpected error occurred when executing this workflow" (При выполнении этого рабочего процесса возникла непредвиденная ошибка). В качестве обходного решения проблемы подключитесь к оболочке администрирования (ssh) и выполните следующее:

```

ghe-actions-console -s actions -c "Queue-ServiceJob -JobId 4DB1F4CF-19FD-40E0-A253-91288813DE8B"

```

|
    - "Когда узел реплики в конфигурации с высокой доступностью отключен, {% data variables.product.product_name %} все равно может маршрутизировать на него запросы {% data variables.product.prodname_pages %}, уменьшая доступность {% data variables.product.prodname_pages %} для пользователей."
    - "При включении {% data variables.product.prodname_actions %} для {% data variables.product.prodname_ghe_server %} удаление узла реплики с помощью \"ghe-repl-teardown\" выполняется, но возможен возврат ошибки \"ERROR:Running migrations\"."
    - "Ограничения ресурсов, относящиеся к обработке перехватчиков перед получением, могут приводить к сбою некоторых из них."
