date: '2021-10-28'
sections:
  security_fixes:
    - 'В некоторые файлы журналов могли попадать пароли в виде открытого текста.'
    - 'Некоторые известные ненадежные открытые ключи SSH добавлены в список запрещенных, и их регистрация теперь невозможна. Кроме того, для известных версий GitKraken, создающих ненадежные ключи SSH (7.6.x, 7.7.x и 8.0.0), регистрация новых открытых ключей заблокирована.'
    - 'Пакеты обновлены до последних версий систем безопасности.'
  bugs:
    - 'Возможен сбой восстановления Enterprise Server в режиме кластеризации, если оркестратор неработоспособен.'
    - 'Некоторые элементы приложения не работали для пользователей, являющихся владельцами множества организаций.'
    - 'Исправлена ссылка на https://docs.github.com.'
  changes:
    - 'Оптимизирована производительность просмотра и заданий в репозиториях с множеством ссылок.'
  known_issues:
    - "Реестр npm для {% data variables.product.prodname_registry %} больше не возвращает значение времени в ответах с метаданными. Это изменение позволяет существенно улучшить производительность. Все данные, необходимые для возврата значения времени в ответе с метаданными, по-прежнему доступны, и мы возобновим этот возврат в будущем, как только имеющиеся проблемы с производительностью будут решены."
    - "Злоумышленник мог создать первого пользователя с правами администратора на новом, только что настроенном сервере {% data variables.product.prodname_ghe_server %}, не имеющем пользователей."
    - Настраиваемые правила брандмауэра удаляются в процессе обновления.
    - "Отслеживаемые файлы Git LFS, [отправленные через веб-интерфейс](https://github.com/blog/2105-upload-files-to-your-repositories), ошибочно добавлялись напрямую в репозиторий."
    - "Невозможно закрывать проблемы, если они содержат постоянную ссылку на BLOB-объект в том же репозитории с путем, длина которого превышает 255 символов."
    - "Когда в GitHub Connect включен параметр \"Пользователи могут выполнять поиск на GitHub.com\", результаты поиска на GitHub.com не включают проблемы в частных и внутренних репозиториях."
    - "При включении {% data variables.product.prodname_actions %} для {% data variables.product.prodname_ghe_server %} удаление узла реплики с помощью \"ghe-repl-teardown\" выполняется, но возможен возврат ошибки \"ERROR:Running migrations\"."
    - "Ограничения ресурсов, относящиеся к обработке перехватчиков перед получением, могут приводить к сбою некоторых из них."
