date: '24.09.2021'
sections:
  security_fixes:
    - '**ВЫСОКИЙ.** Выявлена уязвимость, связанная с обходом каталога, в {% data variables.product.prodname_ghe_server %}, которую злоумышленники могли эксплуатировать при построении сайта {% data variables.product.prodname_pages %}. Управляемые пользователем параметры конфигурации, используемые {% data variables.product.prodname_pages %}, не имели достаточных ограничений и позволяли читать файлы в экземпляре {% data variables.product.prodname_ghe_server %}. Чтобы злоумышленник смог эксплуатировать эту уязвимость, ему требовалось разрешение для создания и построения сайта {% data variables.product.prodname_pages %} в экземпляре {% data variables.product.prodname_ghe_server %}. Эта уязвимость затрагивала все версии {% data variables.product.prodname_ghe_server %} до 3.1.8. Она устранена в версиях 3.1.8, 3.0.16 и 2.22.22. Это результат неполного исправления для CVE-2021-22867. Об этой уязвимости сообщается посредством программы GitHub Bug Bounty. Ей назначен код CVE-2021-22868. {% comment %} https://github.com/github/pages/pull/3361, https://github.com/github/pages/pull/3357 {% endcomment %}'
    - '**СРЕДНИЙ.** Уязвимость из-за ненадлежащего контроля доступа в {% data variables.product.prodname_ghe_server %} позволила заданию рабочего процесса выполняться в локальной группе средств выполнения тестов, к которой у него не должно быть доступа. Это влияет на клиентов, которые используют локальные группы средств выполнения тестов для контроля доступа. Репозиторий с доступом к одной группе средств выполнения тестов предприятия мог получать доступ ко всем группам средств выполнения тестов предприятия из-за ненадлежащих проверок подлинности при выполнении запроса. Это могло приводить к непреднамеренному выполнению кода неправильной группой средств выполнения тестов. Эта уязвимость затрагивала все версии {% data variables.product.prodname_ghe_server %} 3.0.0–3.0.15 и 3.1.0–3.1.7 была устранена в выпусках 3.0.16 и 3.1.8. Ей присвоен код CVE-2021-22869. {% comment %} https://github.com/github/enterprise2/pull/27013 {% endcomment %}'
  bugs:
    - 'Количества в рабочей роли Resque отображались неправильно в режиме обслуживания. {% comment %} https://github.com/github/enterprise2/pull/26899, https://github.com/github/enterprise2/pull/26883 {% endcomment %}'
    - 'Объем выделенной памяти Memcached мог быть равен нулю в режиме кластеризации. {% comment %} https://github.com/github/enterprise2/pull/26928, https://github.com/github/enterprise2/pull/26832 {% endcomment %}'
    - 'Непустые двоичные файлы отображались с неправильным типом файла и размером на вкладке запроса на вытягивание "Файлы". {% comment %} https://github.com/github/github/pull/192810, https://github.com/github/github/pull/172284, https://github.com/github/coding/issues/694 {% endcomment %}'
    - 'Исправляет сборки {% data variables.product.prodname_pages %}, чтобы они учитывали параметр NO_PROXY устройства. Это относится к устройствам, настроенным только с использованием прокси-сервера. (Обновление от 30.09.2021 г.) {% comment %} https://github.com/github/pages/pull/3360 {% endcomment %}'
    - 'Конфигурация GitHub Connect исходного экземпляра всегда восстанавливалась в новые экземпляры, даже если параметр "--config" для "ghe-restore" не использовался. Это приводило к конфликту с подключением GitHub Connect и синхронизацией лицензий, если и исходный экземпляр, и целевой экземпляр были подключены к сети одновременно. Исправление требует также обновления backup-utils до 3.2.0 или более поздней версии. [Обновлено: 18.11.2021 г.]'
  known_issues:
    - "Реестр npm {% data variables.product.prodname_registry %} больше не возвращает значение времени в откликах метаданных. Это было сделано, чтобы предусмотреть существенные улучшения производительности. Мы продолжим хранить все данные, необходимые для возврата значения времени в качестве части отклика метаданных и возобновим возврат этого значения в будущем, как только решим существующие проблемы с производительностью."
    - "Злоумышленник мог создать первого пользователя с правами администратора на новом, только что настроенном сервере {% data variables.product.prodname_ghe_server %}, не имеющем пользователей."
    - Пользовательские правила брандмауэра удалены во время процесса обновления.
    - "Отслеженные файлы Git LFS [отправленные через веб-интерфейс](https://github.com/blog/2105-upload-files-to-your-repositories) ошибочно добавлены непосредственно в репозиторий."
    - "Проблемы невозможно закрыть, если они содержат постоянную ссылку на BLOB-объект в том же репозитории, в котором длина пути к файлу BLOB-объекта более 255 символов."
    - "Когда в GitHub Connect включен параметр \"Пользователи могут выполнять поиск на GitHub.com\", результаты поиска на GitHub.com не включают проблемы в частных и внутренних репозиториях."
    - "Если {% data variables.product.prodname_actions %} включен для {% data variables.product.prodname_ghe_server %}, удаление узла реплики с ghe-repl-teardown будет выполнено успешно, но может возвращаться ERROR:Running migrations."
    - "Ограничения ресурсов, относящиеся к обработке перехватчиков предварительного получения могут привести к сбою некоторых из них."
