date: '2022-06-09'
sections:
  security_fixes:
    - 'В пакетах обновлены системы безопасности до последних версий.'
  bugs:
    - 'Внутренний скрипт для проверки имен узлов в файле конфигурации {% data variables.product.prodname_ghe_server %} возвращал ошибку, если строка имени узла начиналась с "." (знака точки).'
    - "В конфигурациях высокого уровня доступности, где имя основного узла было длиннее 60\_символов, MySQL не удавалось настроить"
    - 'Аргумент --gateway был добавлен в команду ghe-setup-network, чтобы разрешить передачу адреса шлюза при настройке параметров сети с использованием командной строки.'
    - "Вложенные изображения, которые были удалены, возвращали ошибку \"500\_— внутренняя ошибка сервера\" вместо ошибки \"404\_— не найдено\"."
    - 'Расчет "максимального количества фиксаций во всем экземпляре", указанный на панели администратора сайта, был неверным.'
    - 'Неверная запись в базе данных для реплик репозитория вызывала повреждение базы данных при выполнении восстановления с использованием {% data variables.product.prodname_enterprise_backup_utilities %}.'
  changes:
    - 'Оптимизировано включение метрик при создании пакета поддержки кластера.'
    - 'В конфигурациях высокого уровня доступности, где Elasticsearch сообщал о действительном желтом статусе, изменения, внесенные в предыдущем исправлении, блокировали команду ghe-repl-stop и не позволяли остановить репликацию. Использование ghe-repo-stop --force теперь заставит Elasticsearch останавливаться, когда служба находится в нормальном или допустимом желтом статусе.'
    - 'При использовании ghe-migrator или экспорте из {% data variables.product.prodname_dotcom_the_website %} миграции не удавалось экспортировать вложения запросов на вытягивание.'
  known_issues:
    - "После обновления до {% data variables.product.prodname_ghe_server %}\_3.3 {% data variables.product.prodname_actions %} может не запускаться автоматически. Чтобы устранить эту проблему, подключите устройство через SSH и выполните команду ghe-actions-start."
    - 'Злоумышленник мог создать первого пользователя с правами администратора на только что настроенном экземпляре {% data variables.product.prodname_ghe_server %} без пользователей.'
    - 'Настраиваемые правила брандмауэра удаляются в процессе обновления.'
    - "Отслеживаемые файлы Git\_LFS, [отправленные через веб-интерфейс](https://github.com/blog/2105-upload-files-to-your-repositories), ошибочно добавлялись напрямую в репозиторий."
    - "Проблемы нельзя закрыть, если они содержат постоянную ссылку на большой двоичный объект в том же репозитории, где путь к файлу большого двоичного объекта превышает 255\_символов."
    - 'Когда параметр Users can search GitHub.com (Пользователи могут выполнять поиск на GitHub.com) включен с {% data variables.product.prodname_github_connect %}, проблемы в частных и внутренних репозиториях не включаются в результаты поиска в {% data variables.product.prodname_dotcom_the_website %}.'
    - 'Реестр npm {% data variables.product.prodname_registry %} больше не возвращает значение времени в ответах метаданных. Это изменение позволяет существенно улучшить производительность. Мы продолжим хранить все данные, необходимые для возврата значения времени в качестве части ответа метаданных, и возобновим возврат этого значения в будущем, как только решим существующие проблемы с производительностью.'
    - 'Ограничения ресурсов, относящиеся к обработке перехватчиков перед получением, могут приводить к сбою некоторых из них.'
    - 'Параметры хранилища {% data variables.product.prodname_actions %} нельзя проверить и сохранить в {% data variables.enterprise.management_console %}, когда выбран Force Path Style (Принудительно задать стиль пути). Их нужно настраивать с помощью служебной программы командной строки ghe-actions-precheck.'
    - '{% data reusables.release-notes.ghas-3.4-secret-scanning-known-issue %}'
