date: '2022-02-01'
sections:
  security_fixes:
    - '**MEDIA**: Las llamadas API de análisis de secretos podían devolver alertas para repositorios de fuera del ámbito de la solicitud.'
    - 'Los paquetes se han actualizado a las últimas versiones de seguridad.'
  bugs:
    - 'Las páginas no estaban disponibles después de una rotación de secretos de MySQL hasta que "nginx" se reiniciaba manualmente.'
    - 'Las migraciones podían producir un error cuando {% data variables.product.prodname_actions %} estaba habilitado.'
    - 'Al configurar la programación de mantenimiento con una fecha ISO 8601, la hora programada real no coincidía debido a que la zona horaria no se transformaba a UTC.'
    - 'Los mensajes de errores espurios relacionados con "cloud-config.service" se generaban en la consola.'
    - 'El número de versión no se actualizaba correctamente después de instalar una revisión en caliente utilizando "ghe-cluster-each".'
    - 'Varios trabajos de limpieza de tabla de webhook podían ejecutarse simultáneamente, lo que ocasionaba contención de recursos e incrementaba el tiempo de ejecución del trabajo.'
    - 'Cuando se ejecutaba desde la principal, "ghe-repl-teardown" en una réplica no quitaba la réplica del grupo de disponibilidad de MSSQL.'
    - 'La capacidad de limitar las notificaciones basadas en correos electrónicos para los usuarios con correos electrónicos en un dominio aprobado o verificado no funcionaba correctamente.'
    - 'Al utilizar la autenticación CAS y habilitar la opción "Reactivar usuarios suspendidos", dichos usuarios no se reactivaban automáticamente.'
    - 'Una migración de base de datos de duración larga relacionada con los ajustes de alertas de seguridad podía retrasar la finalización de la actualización.'
  changes:
    - 'El registro de conexión de datos de GitHub Connect ahora incluye un recuento de la cantidad de usuarios activos e inactivos y el periodo de inactividad configurado.'
  known_issues:
    - 'Después de actualizar a {% data variables.product.prodname_ghe_server %} 3.3, es posible que {% data variables.product.prodname_actions %} no se inicie automáticamente. Para resolver este problema, conéctate al dispositivo mediante SSH y ejecuta el comando "ghe-actions-start".'
    - 'En una instancia recién configurada de {% data variables.product.prodname_ghe_server %} sin ningún usuario, un atacante podría crear el primer usuario administrador.'
    - 'Las reglas de cortafuegos personalizadas se eliminan durante el proceso de actualización.'
    - 'Los archivos supervisados de Git LFS [cargados desde la interfaz web](https://github.com/blog/2105-upload-files-to-your-repositories) se agregan de manera incorrecta y directa al repositorio.'
    - "Las incidencias no se pueden cerrar si contienen un enlace permanente a un blob del mismo repositorio en el que la ruta es mayor de 255\_caracteres."
    - 'Cuando se habilita "Los usuarios pueden buscar en GitHub.com" con GitHub Connect, las incidencias en los repositorios privados e internos no se incluyen en los resultados de la búsqueda de GitHub.com.'
    - 'El registro npm de {% data variables.product.prodname_registry %} ya no devuelve un valor de hora en las respuestas de metadatos. Esto se hacía para permitir mejoras de rendimiento importantes. Seguimos teniendo todos los datos necesarios para devolver un valor de tiempo como parte de la respuesta de metadatos y reanudaremos la devolución de este valor en el futuro una vez que hayamos resuelto las incidencias de rendimiento existentes.'
    - 'Los límites de recursos que son específicos para procesar enlaces previos a la recepción podrían ocasionar errores en algunos de ellos.'
    - 'Los ajustes de almacenamiento de {% data variables.product.prodname_actions %} no se pueden validar y guardar en la {% data variables.enterprise.management_console %} cuando se selecciona "Forzar estilo de ruta" y, en su lugar, deben configurarse con la utilidad de línea de comandos "ghe-actions-precheck".'
    - 'Las instancias de {% data variables.product.prodname_ghe_server %} 3.3 instaladas en Azure y aprovisionadas con núcleos de CPU 32+ no podían iniciarse debido a un error presente en el kernel de Linux actual. [Actualizado: 08-04-2022]'
    - '{% data reusables.release-notes.ghas-3.4-secret-scanning-known-issue %}'
